"""add_name_to_users

Revision ID: 8581b42393b0
Revises: b7f7c5e7e903
Create Date: 2021-08-19 23:55:14.732387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8581b42393b0'
down_revision = 'b7f7c5e7e903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
