name: Lint

on:
  push:
    branches:
      - main
  pull_request_target:

permissions:
  checks: write
  contents: read

jobs:
  setup-prettier:
    name: Setup Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - name: Checkout repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install Node.js dependencies
        run: yarn install

      - name: Lint
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_dir: ./frontend

  setup-flake8:
    name: Setup Flake8
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository (push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v2

      - name: Checkout repository (pull_request_target)
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install flake8

      - name: Lint
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
          flake8_dir: ./backend
